/* Generated By:JavaCC: Do not edit this line. SelectorParserConstants.java */
package org.cdlib.xtf.textEngine.facet;

public interface SelectorParserConstants {

  int EOF = 0;
  int POUND = 4;
  int DOUBLE_COLON = 5;
  int COLON = 6;
  int BAR = 7;
  int STAR = 8;
  int OPEN_BRACKET = 9;
  int CLOSE_BRACKET = 10;
  int OPEN_PAREN = 11;
  int CLOSE_PAREN = 12;
  int DASH = 13;
  int EQUAL = 14;
  int NUMBER = 15;
  int TERM = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"#\"",
    "\"::\"",
    "\":\"",
    "\"|\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"=\"",
    "<NUMBER>",
    "<TERM>",
  };

}
