/* Generated By:JavaCC: Do not edit this line. XTFTokenizerConstants.java */
package org.cdlib.xtf.textIndexer.tokenizer;

public interface XTFTokenizerConstants {

  int EOF = 0;
  int BASIC = 1;
  int APOSTROPHE = 2;
  int ACRONYM = 3;
  int COMPANY = 4;
  int EMAIL = 5;
  int HOST = 6;
  int NUM = 7;
  int SYMBOL = 8;
  int ALPHANUM = 9;
  int P = 10;
  int HAS_DIGIT = 11;
  int ALPHA = 12;
  int LETTER = 13;
  int CJK = 14;
  int DIGIT = 15;
  int OPT_START = 16;
  int OPT_END = 17;
  int NOISE = 18;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<BASIC>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<SYMBOL>",
    "<ALPHANUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<OPT_START>",
    "<OPT_END>",
    "<NOISE>",
  };

}
