/* Generated By:JavaCC: Do not edit this line. XTFTokenizerConstants.java */
package org.cdlib.xtf.textIndexer.tokenizer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XTFTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BASIC = 1;
  /** RegularExpression Id. */
  int APOSTROPHE = 2;
  /** RegularExpression Id. */
  int ACRONYM = 3;
  /** RegularExpression Id. */
  int COMPANY = 4;
  /** RegularExpression Id. */
  int EMAIL = 5;
  /** RegularExpression Id. */
  int HOST = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int SYMBOL = 8;
  /** RegularExpression Id. */
  int ALPHANUM = 9;
  /** RegularExpression Id. */
  int P = 10;
  /** RegularExpression Id. */
  int HAS_DIGIT = 11;
  /** RegularExpression Id. */
  int ALPHA = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int CJK = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int OPT_START = 16;
  /** RegularExpression Id. */
  int OPT_END = 17;
  /** RegularExpression Id. */
  int NOISE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<BASIC>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<SYMBOL>",
    "<ALPHANUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<OPT_START>",
    "<OPT_END>",
    "<NOISE>",
  };

}
