/* Generated By:JavaCC: Do not edit this line. XTFTokenizerConstants.java */
package org.cdlib.xtf.textIndexer.tokenizer;

public interface XTFTokenizerConstants {

  int EOF = 0;
  int ALPHANUM = 1;
  int APOSTROPHE = 2;
  int ACRONYM = 3;
  int COMPANY = 4;
  int EMAIL = 5;
  int HOST = 6;
  int NUM = 7;
  int SYMBOL = 8;
  int P = 9;
  int HAS_DIGIT = 10;
  int ALPHA = 11;
  int LETTER = 12;
  int CJK = 13;
  int DIGIT = 14;
  int XTF_SPECIAL = 15;
  int NOISE = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<SYMBOL>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<XTF_SPECIAL>",
    "<NOISE>",
  };

}
