/* Generated By:JavaCC: Do not edit this line. FreeformQueryParserConstants.java */
package org.cdlib.xtf.textEngine.freeform;

public interface FreeformQueryParserConstants {

  int EOF = 0;
  int AND = 1;
  int OR = 2;
  int NOT = 3;
  int PLUS = 4;
  int QUOTE = 5;
  int COLON = 6;
  int OPEN_PAREN = 7;
  int CLOSE_PAREN = 8;
  int BASIC = 9;
  int APOSTROPHE = 10;
  int ACRONYM = 11;
  int COMPANY = 12;
  int EMAIL = 13;
  int HOST = 14;
  int NUM = 15;
  int SYMBOL = 16;
  int ALPHANUM = 17;
  int P = 18;
  int HAS_DIGIT = 19;
  int ALPHA = 20;
  int LETTER = 21;
  int CJK = 22;
  int DIGIT = 23;
  int NOISE = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"+\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<BASIC>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<SYMBOL>",
    "<ALPHANUM>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<NOISE>",
  };

}
